config/routes.rb
Rails.application.routes.draw do
  resources :holidays
  resources :plants
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "holidays#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/holiday.rb
class Holiday < ApplicationRecord
	validates :holday, presence: true, uniqueness: true
end

app/models/plant.rb
class Plant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: %i[ show edit update destroy ]

  # GET /holidays or /holidays.json
  def index
    @nxt = Holiday.where("holday >= ?", Date.today).order(holday: :asc).first
    setup_holidays
  end

  # GET /holidays/1 or /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new
  end

  # GET /holidays/1/edit
  def edit
  end

  # POST /holidays or /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)
    # if @question.save
    #   redirect questions_path, :notice => "Successfully created question."
    # else
    #   setup_questions
    #   render :action => :index
    # end
    # binding.pry
    respond_to do |format|
      if @holiday.save
        format.html { redirect_to holidays_url, notice: "Holiday was successfully created." }
        format.json { render :show, status: :created, location: @holiday }
      else
        setup_holidays
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1 or /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to holiday_url(@holiday), notice: "Holiday was successfully updated." }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1 or /holidays/1.json
  def destroy
    @holiday.destroy

    respond_to do |format|
      format.html { redirect_to holidays_url, notice: "Holiday was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def holiday_params
      params.require(:holiday).permit(:holday, :date_details)
    end

    def setup_holidays
    if params[:search] && !params[:clear].present?
    search_term = params[:search].downcase.gsub(/\s+/, "")
    @holidays = Holiday.where("holday >= ?", Date.today).order(holday: :desc).select { |holyday| holyday.date_details.include?(search_term) || holyday.holday.strftime("%d %b %Y").to_s.downcase.include?(search_term)}
    else
      @holidays = Holiday.where("holday >= ?", Date.today).order(holday: :desc)
      params[:search]=nil
    end

    # or any other method to fetch all your questions

    @holiday ||= Holiday.new
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: %i[ show edit update destroy ]

  # GET /plants or /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1 or /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants or /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to plant_url(@plant), notice: "Plant was successfully created." }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1 or /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to plant_url(@plant), notice: "Plant was successfully updated." }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1 or /plants/1.json
  def destroy
    @plant.destroy

    respond_to do |format|
      format.html { redirect_to plants_url, notice: "Plant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plant_params
      params.require(:plant).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/holidays/_form.html.erb
<% if holiday.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h6><%= pluralize(holiday.errors.count, "error") %> prohibited this holiday from being saved:</h6>
      <ul>
        <% holiday.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class = "container bg-light">
<div class="d-flex justify-content-center">
<%= form_with(model: holiday,  :html => {:class => 'row row-cols-lg-auto g-3 align-items-center needs-validation'}) do |form| %>
  
   <div class="col-12">
    <%= form.label :holy_day, style: "display: block" %>
   </div>

  <div class="col-12">
    <%#= form.label :holy_day, style: "display: block" %>
    <%= form.date_field :holday ,placeholder: "Enter Holyday", class:"form-control" %>
  </div>

  <div class="col-12">
    <%#= form.label :date_details, style: "display: block" %>
    <%= form.text_field :date_details,placeholder: "Enter Holiday Details", :type => "text", class:"form-control"%>
  </div>

  <div class="col-auto">
    <%= form.button "ADD", class:"btn btn-success", method: :submit %>
  </div>
  <div class="col-auto">
    <%= link_to 'Cancel', root_path, class:"btn btn-primary"  %>
  </div>
<% end %>
</div>
</div>

<!-- <div class="span12">
    
<form accept-charset="UTF-8" action="/admin/clients" class="well form-inline form-search" method="get"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"></div>
  <fieldset>
    <h3><center> Add Holiday </center> </h3><br> 
    <span class="floatl date" style="padding-left:51px; width:200px"> Date: 
          
            <input class="input-small date-picker" id="reference_detail_signed_date" name="reference_detail[signed_date]" placeholder="dd/mm/yyyy" size="30" style="width:150px" type="text" data-parsley-date="true" data-parsley-ui-enabled="false"><a class="btn btn-mini picker"><i class="icon-calendar"></i></a>

        </span>
        <span style="padding-left:51px">Position:  <input size="40" style="width:200px" type="text" value="TEST"></span>
        <span style="padding-left:40px">
        <input class="btn btn-primary" name="commit" type="submit" value="Add" style="padding-left:12px"></span>
  </fieldset>
  
</form>
  </div>
  <div class="span12">

  
 <table class="table table-striped">
  <tbody>
    <tr>
      <th class="header">Date</th>
      <th class="header">Date Details</th>
      <th class="header">Actions</th>
    </tr>
    <tr>
      <td><strong>
      17 Mar 2022
      </strong></td>
      <td>St Patrick's Day</td>
      <td> Detele </td>
     </tr>
       <tr>
      <td><strong>
       15 April 2022
      </strong></td>
      <td>Good Friday</td>
      <td> Detele </td>
       </tr>
    </tbody>
   </table>

   -->

app/views/holidays/_holiday.html.erb
<div id="<%= dom_id holiday %>">
  <p>
    <strong>Holi day:</strong>
    <%= holiday.holday %>
  </p>

  <p>
    <strong>Date details:</strong>
    <%= holiday.date_details %>
  </p>

</div>

app/views/holidays/edit.html.erb
<h1>Editing holiday</h1>

<%= render "form", holiday: @holiday %>

<br>

<div>
  <%= link_to "Show this holiday", @holiday %> |
  <%= link_to "Back to holidays", holidays_path %>
</div>

app/views/holidays/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-success"><center>Holidays</center></h1>
<br>
<%= render "form", holiday: @holiday %>

<br>
<% if @nxt.present? %>
<div class = "container d-flex justify-content-center">
<div class="alert alert-primary" role="alert">
  <h4 class="alert-heading">Next Holiday!</h4>
  <%= @nxt.holday.strftime("%d %B %Y") %>
</div>
</div>
<%end%>

</br>
<div class = "container d-flex justify-content-right">
<div class="input-group d-flex">
  <div class="form-outline">
    <%= form_tag(holidays_url, method: :get) do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag 'Search 🔍',placeholder: "Search.."%>
    <%= submit_tag 'Clear', name: "clear" %>
    <%end%>
</div> </div></div>
</br>
<table class="table table-striped table-success">
  <thead>
    <tr>
      <th scope="col">Sl.no</th>
      <th scope="col">Holday</th>
      <th scope="col">Date Details</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <%count =1 %>
    <% @holidays.each do |holiday| %>
    <tr>
      <th scope="row"><%= count %></th>
      <% count +=1 %>
      <td><%= holiday.holday.strftime("%d %b %Y") %></td>
      <td><%= holiday.date_details %></td>
      <td><%= button_to "Delete", holiday, class:"btn btn-sucess" , method: :delete %></td>
    </tr>
    <%end%>
    </tbody></table>

app/views/holidays/new.html.erb
<h1>New holiday</h1>

<%= render "form", holiday: @holiday %>

<br>

<div>
  <%= link_to "Back to holidays", holidays_path %>
</div>

app/views/holidays/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @holiday %>

<div>
  <%= link_to "Edit this holiday", edit_holiday_path(@holiday) %> |
  <%= link_to "Back to holidays", holidays_path %>

  <%= button_to "Destroy this holiday", @holiday, method: :delete %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-success">
  <div class="container-fluid">
     <%= link_to 'Holiday Finder', root_path, class:"navbar-brand text-light" %> 
  </div></nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Holiday Finder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/plants/_form.html.erb
<%= form_with(model: plant) do |form| %>
  <% if plant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
        <% plant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/plants/_plant.html.erb
<div id="<%= dom_id plant %>">
  <p>
    <strong>Name:</strong>
    <%= plant.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= plant.price %>
  </p>

</div>

app/views/plants/edit.html.erb
<h1>Editing plant</h1>

<%= render "form", plant: @plant %>

<br>

<div>
  <%= link_to "Show this plant", @plant %> |
  <%= link_to "Back to plants", plants_path %>
</div>

app/views/plants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Plants</h1>

<div id="plants">
  <% @plants.each do |plant| %>
    <%= render plant %>
    <p>
      <%#= link_to "Show this plant", plant %>
      <li>  <%= link_to "Show this plant", plant %> <br><%= link_to "Hide", "", class: 'hide', data: {'js-hide-link' => true} %></li>
    </p>
  <% end %>
</div>
<div data-controller="hello"> </div>
<%= link_to "New plant", new_plant_path %>

app/views/plants/new.html.erb
<h1>New plant</h1>

<%= render "form", plant: @plant %>

<br>

<div>
  <%= link_to "Back to plants", plants_path %>
</div>

app/views/plants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @plant %>

<div>
  <%= link_to "Edit this plant", edit_plant_path(@plant) %> |
  <%= link_to "Back to plants", plants_path %>

  <%= button_to "Destroy this plant", @plant, method: :delete %>
</div>